# Generated by Django 4.0.6 on 2022-07-23 08:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_topic_room_host_message_room_topic'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ['-updated', '-created']},
        ),
    ]
